<?php
    declare(strict_types=1);
    $XmlParser = new Volta\Component\Books\ContentParsers\XhtmlParser();
?>

<h1>Appendix</h1>

<p>Here you wil find a list with <abbr>XHTML</abbr> elements in the volta namespace and its usage.</p>

<h2 id="volta:quote">volta:quote</h2>
<?php $xhtml = <<< eol

    <volta:quote href="https://the.link.to/the/source">
    Place your multiline (block)quote here
    </volta:quote>    
    <p>Lorum ipsum and stuf <volta:quote inline="true">place your inline quote here</volta:quote> and more lorum</p>    
    <p>Lorum ipsum and stuf <volta:quote href="https://the.link.to/the/source" inline="true">place your inline quote here</volta:quote> and more lorum</p>

eol; ?>
<div><strong><u>Usage:</u></strong><br>Give all quotes the same look and feel whether this is inline or multilines. Pass an optional source URI to link to the source.</div>
<div><strong><u>Attributes:</u></strong><br>
    &nbsp;&nbsp;&nbsp;&nbsp;<var>href: </var>Specify the URL for the source of the quote <br>
    &nbsp;&nbsp;&nbsp;&nbsp;<var>inline: </var>"false"(default) or "true" to display as multiline (&lt;blockquote&gt;) or inline (&lt;q&gt;) element.
</div>
<div><strong><u>Code:</u></strong><br><pre><code class="language-html"><?=htmlentities($xhtml); ?></code></pre></div>
<div><strong><u>Result:</u></strong><br><?= $XmlParser->getContent($xhtml, $this->getNode()) ?></div>

<h2 id="volta:chuck">volta:chuck</h2>
<?php $xhtml = <<< eol
     <volta:chuck/>
eol; ?>
<div><strong><u>Usage:</u></strong><br>Shows a random Chuck Norris joke</div>
<div><strong><u>Code:</u></strong><br><pre><code class="language-html"><?=htmlentities($xhtml); ?></code></pre></div>
<div><strong><u>Result:</u></strong><br><?= $XmlParser->getContent($xhtml, $this->getNode()) ?></div>


<h2 id="volta:footnote">volta:footnote</h2>
<p>Shows  the footnote as a number and list all at the bottom of a page</p>
        <?php $xhtml = <<< eol
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                labore et dolore magna aliqua.<volta:footnote>Some tekst to be added as a foot note</volta:footnote></p>
                <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
                esse cillum dolore eu fugiat nulla pariatur.<volta:footnote href="With a link">Another footnote with a link</volta:footnote> Excepteur sint occaecat cupidatat non proident, sunt in culpa
                qui officia deserunt mollit anim id est laborum. </p>
                eol; ?>
<div class="box">
<strong><u>Code:</u></strong><br><pre><code class="language-html"><?=htmlentities($xhtml); ?></code></pre>
<strong><u>Result:</u></strong><br><?= $XmlParser->getContent($xhtml, $this->getNode()) ?>
</div>

<h2 id="volta:node">volta:node</h2>
<p>Inserts a link to another node. The attribute <var>path</var> is relative to the root and must start with a slash(/)</p>
        <?php $xhtml = <<< 'eol'
                <ol>
                <li>Path is relative to the root: <volta:node path="/2-Table-of-Contents">"{{DISPLAY_NAME}}"</volta:node></li>
                <li>Defaults to the current page: <volta:node>"{{DISPLAY_NAME}} (page {{INDEX}})"</volta:node></li>
                <li>Get the full URI  <volta:node path="/3-Introduction">"{{URI}}"</volta:node></li>
                <li>With custom tooltip  <volta:node path="/" title="Back to home">"{{NAME}}"</volta:node></li>
                <li>Non exiting page results in an error:<volta:node path="/to-bogus-page">"{{NAME}}"</volta:node></li>
                </ol>
                eol; ?>
<div class="box">
<strong><u>Code:</u></strong><br><pre><code class="language-html"><?=htmlentities($xhtml); ?></code></pre>
<strong><u>Result:</u></strong><br><?= $XmlParser->getContent($xhtml, $this->getNode()) ?>
</div>

<h2 id="volta:highlight">volta:highlight</h2>
<p>Makes use of the <a href="https://highlightjs.org/">highlightjs.js/</a> module</p>
        <?php $xhtml = <<< 'eol'
                <volta:highlight language="html">
                <p>Hello <u>World</u></p>
                </volta:highlight>
                eol; ?>
<div class="box">
<strong><u>Code:</u></strong><br><pre><code class="language-html"><?=htmlentities($xhtml); ?></code></pre>
<strong><u>Result:</u></strong><br><?= $XmlParser->getContent(htmlentities($xhtml), $this->getNode()) ?>
</div>


<h2 id="volta:quiz">volta:quiz</h2>
<h3 id="volta:quiz">volta:question</h3>
<h3 id="volta:answer">volta:answer</h3>

<h2 id="volta:toc">volta:toc</h2>

<h2 id="volta:xhtml">volta:xhtml</h2>